---
title: "Trend in Number of COVID-19 Cases in the US"
author: "Anyu Zhu"
date: "11/9/2021"
output: 
  html_document:
    toc: true
    toc_float: true
---

This page is about trend in the number of COVID-19 cases in the US

```{r}
library(tidyverse)
library(plotly)
library(rvest)
library(ggplot2)
library(lubridate)
```

Import data
```{r}
covid_cum = read_csv("data/covid_cumulative_cases.csv", skip = 2) %>% 
  janitor::clean_names()

covid_day = read_csv("data/covid_daily_cases.csv", skip = 2) %>% 
  janitor::clean_names()

covid_daily = left_join(covid_day, covid_cum, by = "date") %>% 
  select(date, new_cases, total_cases) %>% 
  separate(date, into = c("month","day","year")) %>% 
  mutate(month = factor(month, levels = month.abb)) %>% 
  group_by(year, month) %>% 
  arrange(year, month, day) %>% 
  mutate(date = make_date(year, month, day)) %>% 
  arrange(date)
  
covid_monthly = covid_daily %>% 
  select(-day) %>% 
  summarize(monthly = sum(new_cases))

covid_seasonal = covid_monthly %>% 
  mutate(quarter = recode(month,
    "Jan" = "q1",
    "Feb" = "q1",
    "Mar" = "q1",
    "Apr" = "q2",
    "May" = "q2",
    "Jun" = "q2",
    "Jul" = "q3",
    "Aug" = "q3",
    "Sep" = "q3",
    "Oct" = "q4",
    "Nov" = "q4",
    "Dec" = "q4"
  )) %>% 
  group_by(year, quarter) %>% 
  summarize(quarterly = sum(monthly)) %>% 
  mutate(date = str_c(year, quarter, sep = "_"))

write_csv(covid_seasonal, 'covid_seasonal.csv')
```

Plots
Daily
```{r}
daily_fig = plot_ly(covid_daily) 

daily_fig %>% 
  add_trace(x = ~date, y = ~new_cases, type = "bar", yaxis="y", name = "new") %>% 
  add_trace(x = ~date, y = ~total_cases, type = "scatter", mode = "lines", yaxis = "y2", name = "cumulative") %>% 
  layout(yaxis=list(title = "daily new cases", side="left"),
         yaxis2=list(title = "cumulative cases", side="right",overlaying="y"),
         showlegend=TRUE)
```


Quarterly (to correspond with the consumption data)
```{r}
covid_seasonal %>% 
  plot_ly(x = ~date, y = ~quarterly, type = "bar") 
```

