---
title: "Regional Data"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
resource_files:
- data/state_covid_separate/data_table_for_total_cases__alabama.csv
- data/state_covid_separate/data_table_for_total_cases__alaska.csv
- data/state_covid_separate/data_table_for_total_cases__arizona.csv
- data/state_covid_separate/data_table_for_total_cases__arkansas.csv
- data/state_covid_separate/data_table_for_total_cases__california.csv
- data/state_covid_separate/data_table_for_total_cases__colorado.csv
- data/state_covid_separate/data_table_for_total_cases__connecticut.csv
- data/state_covid_separate/data_table_for_total_cases__delaware.csv
- data/state_covid_separate/data_table_for_total_cases__district_of_columbia.csv
- data/state_covid_separate/data_table_for_total_cases__florida.csv
- data/state_covid_separate/data_table_for_total_cases__georgia.csv
- data/state_covid_separate/data_table_for_total_cases__guam.csv
- data/state_covid_separate/data_table_for_total_cases__hawaii.csv
- data/state_covid_separate/data_table_for_total_cases__idaho.csv
- data/state_covid_separate/data_table_for_total_cases__illinois.csv
- data/state_covid_separate/data_table_for_total_cases__indiana.csv
- data/state_covid_separate/data_table_for_total_cases__iowa.csv
- data/state_covid_separate/data_table_for_total_cases__kansas.csv
- data/state_covid_separate/data_table_for_total_cases__kentucky.csv
- data/state_covid_separate/data_table_for_total_cases__louisiana.csv
- data/state_covid_separate/data_table_for_total_cases__maine.csv
- data/state_covid_separate/data_table_for_total_cases__maryland.csv
- data/state_covid_separate/data_table_for_total_cases__massachusetts.csv
- data/state_covid_separate/data_table_for_total_cases__michigan.csv
- data/state_covid_separate/data_table_for_total_cases__minnesota.csv
- data/state_covid_separate/data_table_for_total_cases__mississippi.csv
- data/state_covid_separate/data_table_for_total_cases__missouri.csv
- data/state_covid_separate/data_table_for_total_cases__montana.csv
- data/state_covid_separate/data_table_for_total_cases__nebraska.csv
- data/state_covid_separate/data_table_for_total_cases__nevada.csv
- data/state_covid_separate/data_table_for_total_cases__new_hampshire.csv
- data/state_covid_separate/data_table_for_total_cases__new_jersey.csv
- data/state_covid_separate/data_table_for_total_cases__new_mexico.csv
- data/state_covid_separate/data_table_for_total_cases__new_york_(excludes_nyc)_.csv
- data/state_covid_separate/data_table_for_total_cases__new_york_city_.csv
- data/state_covid_separate/data_table_for_total_cases__north_carolina.csv
- data/state_covid_separate/data_table_for_total_cases__north_dakota.csv
- data/state_covid_separate/data_table_for_total_cases__northern_mariana_islands.csv
- data/state_covid_separate/data_table_for_total_cases__ohio.csv
- data/state_covid_separate/data_table_for_total_cases__oklahoma.csv
- data/state_covid_separate/data_table_for_total_cases__oregon.csv
- data/state_covid_separate/data_table_for_total_cases__palau.csv
- data/state_covid_separate/data_table_for_total_cases__pennsylvania.csv
- data/state_covid_separate/data_table_for_total_cases__puerto_rico.csv
- data/state_covid_separate/data_table_for_total_cases__republic_of_marshall_islands.csv
- data/state_covid_separate/data_table_for_total_cases__rhode_island.csv
- data/state_covid_separate/data_table_for_total_cases__south_carolina.csv
- data/state_covid_separate/data_table_for_total_cases__south_dakota.csv
- data/state_covid_separate/data_table_for_total_cases__tennessee.csv
- data/state_covid_separate/data_table_for_total_cases__texas.csv
- data/state_covid_separate/data_table_for_total_cases__utah.csv
- data/state_covid_separate/data_table_for_total_cases__vermont.csv
- data/state_covid_separate/data_table_for_total_cases__virgin_islands.csv
- data/state_covid_separate/data_table_for_total_cases__virginia.csv
- data/state_covid_separate/data_table_for_total_cases__washington.csv
- data/state_covid_separate/data_table_for_total_cases__west_virginia.csv
- data/state_covid_separate/data_table_for_total_cases__wisconsin.csv
- data/state_covid_separate/data_table_for_total_cases__wyoming.csv
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(plotly)
```


```{r data_import, warning=FALSE}
#load data for pce by states
total_df =
  read_csv("data/pce_by_state/total.csv", skip = 4) %>% 
  drop_na() %>% 
  janitor::clean_names() %>% 
  rename(state = geo_name, type = description) %>% 
  mutate(t_p = factor("Total")) %>% 
  select(-geo_fips, -line_code) %>% 
  pivot_longer(
    x2016:x2020,
    names_to = "year",
    names_prefix = "x",
    values_to = "Crude"
  ) %>% 
  mutate(year = as.numeric(year))

per_df =
  read_csv("data/pce_by_state/per_capita.csv", skip = 4) %>% 
  drop_na() %>% 
  janitor::clean_names() %>% 
  rename(state = geo_name, type = description) %>% 
  mutate(t_p = factor("Per Capita")) %>% 
  select(-geo_fips, -line_code) %>% 
  pivot_longer(
    x2016:x2020,
    names_to = "year",
    names_prefix = "x",
    values_to = "Crude"
  ) %>% 
  mutate(year = as.numeric(year))

postal_code = 
  read_csv("./data/us_postal_code.csv") %>% 
  janitor::clean_names() %>% 
  select(-abbrev)
  

state_df =
  full_join(total_df, per_df) %>% 
  mutate(
    type = replace(type, type == "Personal consumption expenditures", "Total"),
    type = replace(type, type == "Per capita personal consumption expenditures", "Total")
  )

state_df =
  state_df %>% 
  group_by(state, type, t_p) %>% 
  mutate(Change = round(100 * (Crude - lag(Crude)) / lag(Crude), digit = 1)) %>% 
  pivot_longer(
    Crude:Change,
    names_to = "if_change",
    values_to = "pce"
  ) %>% 
  mutate(if_change = replace(if_change, if_change == "Change", "Percent Change")) %>% 
  ungroup()

state_df = 
  left_join(state_df, postal_code, by = "state") %>% 
  mutate(
    text = paste(state, "\n", round(pce, digit = 1)),
    major_type = case_when(
      type == "Total" ~ "Total",
      type %in% c("Motor vehicles and parts", 
                  "Furnishings and durable household equipment",
                  "Recreational goods and vehicles",
                  "Other durable goods") ~ "Durable Goods",
      type %in% c("Food and beverages purchased for off-premises consumption",
                  "Clothing and footwear",
                  "Gasoline and other energy goods",
                  "Other nondurable goods") ~ "Nondurable Goods",
      type %in% c("Housing and utilities",
                  "Health care",
                  "Transportation services",
                  "Recreation services",
                  "Food services and accommodations",
                  "Financial services and insurance",
                  "Other services") ~ "Services"
    )
  )

#load data for covid by states
read_data_function = function(file_df) {
  
  state_df2 = 
    read_csv(file_df, skip = 2)
  
  return(state_df2)
}
# create a data frame containing all participants
state_2020 =
  tibble(
    files = list.files("./data/state_covid_separate")
  ) %>% 
  mutate(
    path = map(.x = files, ~paste("./data/state_covid_separate", ., sep = "/"))
  ) %>%                                                             # add path
  mutate(
    observations = map(path, read_data_function))

state_2020_tidy =
  state_2020 %>% 
  unnest(cols = "observations") %>% 
  janitor::clean_names() %>% 
  filter(date == "Dec 31 2020") %>%
  select(state, total_cases, total_case_rate_per_100k)

covid_state_df = left_join(state_2020_tidy, postal_code, by = "state") %>%
  drop_na()

jointly_df = 
  left_join(state_df, covid_state_df, by = c("state", "code"))

g = list(
  scope = 'usa',
  projection = list(type = 'albers usa')
)
```


Personal Consumption Expenditures by State
===================================== 

Column {.sidebar data-width=200}
-----------------------------------------------------------------------

```{r for_sidebar}
year_choices = as.list(c(2017:2020))

type_choices = 
  state_df %>% 
  distinct(type) %>% 
  pull()

method_choices = as.list(c("Total", "Per Capita"))

percent_change_choices = as.list(c("Crude", "Percent Change"))

radioButtons(
  "method_choice",
  label = "",
  choices = method_choices,
  selected = "Total"
)

selectInput(
  "year_choice",
  label = h4("Select Year"),
  choices = year_choices,
  selected = "2020"
)

selectInput(
  "type_choice",
  label = h4("Select Type of Product"),
  choices = type_choices,
  selected = "Total"
)

radioButtons(
  "percent_change_choice",
  label = "",
  choices = percent_change_choices,
  selected = "Percent Change"
)
```

Column {.tabset data-width=600}
-----------------------------------------------------------------------

### US Map

```{r us_map}

renderPlotly({
  
  state_df %>% 
    filter(
      t_p == input[["method_choice"]],
      year == input[["year_choice"]],
      type == input[["type_choice"]],
      if_change == input[["percent_change_choice"]]
    ) %>% 
  plot_geo(locationmode = 'USA-states') %>%
    add_trace(
    type = "scattergeo",
    locations = ~code,
    text = ~code,
    mode = "text",
    textfont = list(color = rgb(0,0,0), size = 10),
    hoverinfo = "none"
  ) %>% 
    add_trace(
    z = ~pce, 
    locations = ~code,
    text = ~text,
    color = ~pce, 
    colorscale = list(c(0, 1), c("#f5faff", "#004c8c")),
    hoverinfo = "text",
    colorbar = list(title = "PCE", thickness = 20, x = 1, y = 0.8)
  ) %>% 
  layout(
    title = 'Personal Consumption Expenditures by State',
    geo = g
  )
  
})
```


### PCE with Covid by State

Generally, there is an apparent negative correlation between per capita PCE and Covid Rate.

```{r}
renderPlotly({
  
  jointly_df %>% 
    filter(type == "Total", t_p == "Per Capita", year == 2020, if_change == "Crude") %>% 
    arrange(total_case_rate_per_100k) %>% 
    mutate(state = fct_reorder(state, total_case_rate_per_100k)) %>% 
    plot_ly(x = ~state) %>% 
    add_trace(y = ~pce, type = "scatter", mode = "lines",name = "Per Capita PCE", yaixs = "y") %>% 
    add_trace(y = ~total_case_rate_per_100k, type = "bar", name = "Covid Cases(per 100k)", 
              yaxis = "y2", opacity = 0.6, marker = list(color = 'rgb(158,202,225)'))  %>% 
    layout(title = "Per Capita PCE with Covid Cases, 2020",
           xaxis = list(title = "State"),
           yaxis = list(title = "PCE", side = "left"),
           yaxis2 = list(title = "Covid Cases Rate", side = "right", overlaying = "y"),
           showlegend = TRUE,
           legend = list(xanchor = "center", x = 0.93))
  
})
```


Column {data-width=400}
-----------------------------------------------------------------------

### Description
**PCE by state** is the state counterpart of the nation's personal consumption expenditures (PCE). PCE by state measures the goods and services purchased by or on behalf of households and the net expenditures of nonprofit institutions serving households by state of residence for the 50 states and the District of Columbia. PCE by state reflects spending on activities that are attributable to the residents of a state, even when those activities take place outside of the state.

**Per capita PCE by state** measures average PCE spending per person in a state, and it is calculated as PCE in a state divided by the population of the state.

**Relationship of PCE by state to national PCE.** The U.S. PCE by state differs slightly from the PCE in the national accounts because PCE by state excludes the net expenditures abroad by U.S. residents, which consist of government and private employees’ expenditures abroad less personal remittances in kind to nonresidents. PCE by state, however, does include the travel expenditures abroad by U.S. residents.

<br />

The PCE by state estimates were impacted by the response to the spread of COVID-19, as governments issued and lifted "stay-at-home" orders. This led to rapid changes in demand and consumers canceled, restricted, or redirected their spending. 

State PCE decreased 2.6 percent in 2020 after increasing 3.7 percent in 2019, according to statistics released today by the U.S. Bureau of Economic Analysis (BEA). The percent change in PCE across all 50 states and the District of Columbia ranged from 1.2 percent in Idaho and Utah to –5.8 percent in the District of Columbia. 

PCE increased in only four states, Idaho, Utah, Montana, and Arkansas.

Across all states and the District of Columbia, per capita PCE was $42,635. Per capita PCE by state ranged from a high of $52,001 in Massachusetts to a low of $32,358 in Mississippi. Per capita PCE in the District of Columbia was $65,169. 

Expenditures on food services and accommodations, recreation services, and health care were the leading contributors to the decrease nationally:

• Food services and accommodations decreased 20.5 percent nationally and was the largest contributor to decreases in the District of Columbia and 27 states including Hawaii and New York; it was the second largest contributor to decreases in 11 states.

• Recreation services decreased 28.6 percent nationally and was the largest contributor to decreases in 4 states including California.

• Health care decreased 6.1 percent nationally and was the largest contributor to decreases in 12 states including Alaska.



Trend by States
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
state_choices = 
  state_df %>% 
  distinct(state) %>% 
  pull()

majortype_choices = 
  state_df %>% 
  filter(major_type != "Total") %>% 
  distinct(major_type) %>% 
  pull()

selectInput(
  "state_choice",
  label = h3("Select State"),
  choices = state_choices,
  selected = "New York"
)

selectInput(
  "major_type_choice",
  label = h3("Select Major Type"),
  choices = majortype_choices,
  selected = "Durable Goods"
)
```

Column {.tabset}
-----------------------------------------------------------------------

### Line Chart

```{r}
renderPlotly({
  
  state_df %>% 
    filter(
      state == input[["state_choice"]],
      type != "Total",
      major_type == input[["major_type_choice"]],
      t_p == "Total",
      if_change == "Crude"
    ) %>% 
    group_by(type) %>% 
    plot_ly(x = ~year) %>% 
    add_trace(y = ~pce, type = "scatter", mode = "lines", yaixs = "y", color = ~type, colorscale = "viridis") %>% 
    layout(title = "PCE Trend by States",
           xaxis = list(title = "Year", dtick = 1),
           yaxis = list(title = "PCE", side = "left"),
           showlegend = TRUE
           )
  
})
```

### Description

