---
title: "Project Report"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

## Motivation

Begin with the pandemic’s early stages in spring 2020, the COVID-19 pandemic has drastically altered the everyday lives of billions of people, with potential impacts on consumption.

The epidemic also affected the way people consumed; people worked from home and went out less due to restrictions on avoiding gatherings and dine-in restaurants. We believe this will lead to a collapse in consumption mainly in the services sector. However, consumption in entertainment, such as video games, may increase as a result of the significant increase in time spent at home, meaning that the decline in consumption of goods may be smaller.

To confirm our conjecture, our group wants to analyze the results of the change in consumption levels from the data sets.

## Related Work

The following resources are samples of what inspired this project:

1."The decline and recovery of consumer spending in the US" Brookings, December 14, 2020 [link](https://www.brookings.edu/blog/future-development/2020/12/14/the-decline-and-recovery-of-consumer-spending-in-the-us/)

2."Will New York renew mask mandate and COVID-19 restrictions? What to know as cases surge", Democrat and Chronicle, November 18, 2021[link](https://www.democratandchronicle.com/story/news/2021/11/18/new-york-renew-mask-mandate-and-covid-restrictions-what-know/8654736002/)

## Research Design

### Initial Hypothesis

Our project is designed to investigate how the Covid-19 pandemic has affected US people’s consuming behavior. We intend to research whether there are changes to people's total personal consumption expenditure(PCE) and their consumption pattern since the pandemic happened in March 2020. We are also interested in how much people’s consuming behaviors has recovered since the society is gradually returning to normal life in 2021. 

Hypothesis: 

### Evolution of Analytic Questions

• There is evidence that the severity of Covid-19 varies among states, so as the PCE. To address the differences, we analyzed the data by states by drawing maps based on Covid 19 and consumption expenditure data. 

• The pandemic has lasted for two years, thus using the data since the pandemic for modeling is insufficient and biased. To address this problem, we build a prediction model of PCE based on income and consumption data since 1967. To test the hypothesis, we predict the consumption data in 2020 and 2021 using the model and compare it to the real-world data.

• The inflation and recent rises in prices potentially affect the PCE data as well. To address this, we considered inflation and analyze using chained dollars. which is a method of adjusting real dollar amounts for inflation over time, allowing the comparison of figures from different years.

### New Questions Identified During Analysis

PCE is also affected by the trend of personal incomes, and government’s laws to support and sustain businesses and individuals through the pandemic. In addition, we decided to also examine how the pandemic has impacted personal incomes and savings in U.S., and whether they matched the changing of PCE. In this process, we can obtain more comprehensive understanding of how the pandemic has influenced people’s economic conditions and behaviors in different aspects.

## Data

### Data Sources

<p>• Personal Consumption Expenditures by Major Type of Product and by Major Function:

https://www.bea.gov/data/consumer-spending/main

<p>• Personal Consumption Expenditures by Major Type of Product and by Major Function, by State:

https://www.bea.gov/data/consumer-spending/state

<p>• Trends in Number of COVID-19 Cases and Deaths in the US Reported to CDC: 

https://covid.cdc.gov/covid-data-tracker/#trends_dailycases

### Variables of Interest

**Consumption Expenditure**
<p>• `functions`: the different functions of the goods.
<p>• `time`: different quarters.
<p>• `consumption`: the total amount of consumptions.

**COVID Cumulative Cases**
<p>• `state`
<p>• `date`: the date when the data collected.
<p>• `total_cases`: the amount to the cases diagnosed within and before the date.

**COVID Daily Cases**
<p>• `state`
<p>• `date`: the date when the data collected.
<p>• `total_cases`: the amount to the cases diagnosed within the date.

**Personal Income and Savings**


## Data cleaning

<P>  From `Consumption Function`, we deleted unneeded rows (whose row numbers are greater than 28, since these rows are not showing the function of the goods), made a `time` variable that sorted the years and the quarter. We renamed `Household consumption expenditures (for services)` to `household`, and renamed `Final consumption expenditures of nonprofit institutions serving households (NPISHs)1` to `nonprofit consumption`, since the original names are too long. 

<P>  From `COVID Cumulative Cases`, we combine the new case data frame and the cumulative case data frame together and seperate the time points into `month`, `day` and `year`. Then we created a new variable named `date` that rewrite the date into the form of `YYYY-MM-DD`.

<P>  In order to compare the covid case data and the comsumption data, we made a new data frame named `covid_seasonal` that reorder the covid case data by season (quarter 1 = January - March, quarter 2 = April - June, quarter 3 = July - September, quarter 4 = October - December). Then we write this data frame into a new .csv document.

## Exploratory Analysis

### US Covid 19

### National Consumption Expenditure Data

### Income Data


## Regression Analysis

<p> Using the personal consumption expenditure (PCE) and income data, we aimed to investigate how the COVID-19 pandemic influence people's spending patterns. We know that one's consumption is associate with one's income, so we built a MLR model from income data and made predictions for PCE. Our variables of interest include `wages and salaries`, `supplements to wages and salaries`, `social security`, `medicare`, `personal current taxes`, and the outcome `PCE`.

<p> We hypothesized that the PCE pattern has changed with respect to income for pre- v.s. in-pandemic periods. To test this hypothesis, we fitted a MLR model using data from year 1967-2018, the "pre-pandemic" period. We then used this model to predict for PCE outcomes for a pre-pandemic year, 2019, and a in-pandemic year, 2020, respectively. Then we compared if there is significant difference in the root mean square errors (RMSE) between the pre-pandemic and in-pandemic periods. If there is significant difference between them, we can conclude that there is enough evidence showing that the PCE patterns has changed during the pandemic and vice versa. 

<p> Our model fits the data well because our $R^2$ value is $> 99\%$. We then used multiple diagnostic methods to evaluate the model. The QQ-plot indicates the distribution of residuals are normal. The Scale-location plot shows that the residuals are spread equally along the range of predictors. And the residuals-leverage plot shows that no outlier is influential. Therefore, we were confident to proceed our analysis with the MLR model. 

<p> Giving the MLR model and its predictions for PCE, we explored the difference in the root mean square errors (RMSE) of the model between the pre-pandemic and in-pandemic periods in dollars. To obtain a pool of RMSE data, we utilized bootstrapping method on data of year 2019 and 2020. The results were tested via the t-test, which indicated a significant difference between the RMSEs of the two years. This indicated that people's spending pattern has changed during the pandemic, and this change could not fully explain by variations of their incomes. 

<p> Therefore, there is evidence showing that the COVID-19 pandemic has affected people's spending patterns. 


## Discussion

## Conclusions